// Authentication
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Dashboard
export const GET_DASHBOARD_LAYOUT = "GET_DASHBOARD_LAYOUT";
export const SAVE_DASHBOARD_LAYOUT = "SAVE_DASHBOARD_LAYOUT";

// Chart
export const SET_ROUNDLINE_SUBSCRIPTION = "SET_ROUNDLINE_SUBSCRIPTION";
export const SET_STRAIGHTLINE_SUBSCRIPTION = "SET_STRAIGHTLINE_SUBSCRIPTION";
export const SET_BAR_SUBSCRIPTION = "SET_BAR_SUBSCRIPTION";
export const SET_COLOUREDLINE_SUBSCRIPTION = "SET_COLOUREDLINE_SUBSCRIPTION";
export const SET_PIE_SUBSCRIPTION = "SET_PIE_SUBSCRIPTION";
export const SET_MULTIPLEBAR_SUBSCRIPTION = "SET_MULTIPLEBAR_SUBSCRIPTION";
export const SET_COLOUREDLINES_SUBSCRIPTION = "SET_COLOUREDLINES_SUBSCRIPTION";
export const SET_SPEEDOMETER_SUBSCRIPTION = "SET_SPEEDOMETER_SUBSCRIPTION";
export const SET_DONUT_SUBSCRIPTION = "SET_DONUT_SUBSCRIPTION";
export const SET_PLAINMESSAGES_SUBSCRIPTION = "SET_PLAINMESSAGES_SUBSCRIPTION";

export const SET_ROUNDLINE_DATA = "SET_ROUNDLINE_DATA";
export const SET_STRAIGHTLINE_DATA = "SET_STRAIGHTLINE_DATA";
export const SET_BAR_DATA = "SET_BAR_DATA";
export const SET_COLOUREDLINE_DATA = "SET_COLOUREDLINE_DATA";
export const SET_PIE_DATA = "SET_PIE_DATA";
export const SET_MULTIPLEBAR_DATA = "SET_MULTIPLEBAR_DATA";
export const SET_COLOUREDLINES_DATA = "SET_COLOUREDLINES_DATA";
export const SET_SPEEDOMETER_DATA = "SET_SPEEDOMETER_DATA";
export const SET_DONUT_DATA = "SET_DONUT_DATA";
export const SET_PLAINMESSAGES_DATA = "SET_PLAINMESSAGES_DATA";
